services:
  oidc-proxy:
    # Option 1: Build locally
    build: .
    # image: ghcr.io/firlevapz/keycloak-oidc-proxy:latest
    env_file:
      - .env  # Load from .env file if it exists
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
