version: '3.8'

services:
  oidc-proxy:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env  # Load from .env file if it exists
    environment:
      # Required: Replace with your actual OIDC configuration URL
      OIDC_CONFIGURATION_URL: "${OIDC_CONFIGURATION_URL:-https://auth.hoad.at/application/o/audiobookshelf/.well-known/openid-configuration}"
      # Optional: Set log level (trace, debug, info, warn, error, fatal, panic)
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      # Optional: Set port (default: 8080)
      PORT: "${PORT:-8080}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Uncomment the following lines if you want to use an external network
    # networks:
    #   - oidc-proxy-network

# Uncomment if you want to create a custom network
# networks:
#   oidc-proxy-network:
#     driver: bridge
